package com.wsunitstats.domain.submodel.research;

import jakarta.persistence.Embeddable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Is not related to game files data. Generated by the app
 */
@Embeddable
@Getter
@Setter
@ToString
public class UpgradeMetadataModel {
    private String description;
}
